msg-check: "&b&lBot&d&lFilter&7>> &fОжидайте завершения проверки..."
msg-check-2: "&b&lBot&d&lFilter&7>> &fНажимите на кнопку с &aЗЕЛЁНОЙ&f шерстью."
msg-check-sus: "&b&lBot&d&lFilter&7>> &aПроверка пройдена"
#line1;line2
msg-check-title: "&b&lBot&d&lFilter;&fОжидайте завершения проверки..."
msg-check-title-sus: "&b&lBot&d&lFilter&r;&aПроверка пройдена.."
msg-press-button-title: "&fНажимите на кнопку с ;&aЗЕЛЁНОЙ&f шерстью."
error-many-checks: "&b&lBot&d&lFilter&7>> &cОчень много проверок с одного IP адресса. Попробуйте зайти через 10 минут&7>> &4ERROR #0" 
error-not-a-player: "&b&lBot&d&lFilter&7>> &cСкорее всего вы не игрок &a(Если вы используете читы, выключите их) &7>> &4ERROR #1"
error-wrong-button: "&b&lBot&d&lFilter&7>> &cВы нажали на неверную кнопку&7>> &4ERROR #5"
error-proxy-detected: "&b&lBot&d&lFilter&7>> &cВаше соединение признано нелегитимным&7>> &4ERROR #2"
error-many-pos-packets: "&b&lBot&d&lFilter&7>> &cВы посылаете очень много пакетов&7>> &4ERROR #3"
error-cannot-use-button : "&b&lBot&d&lFilter&7>> &cНеправильная позиция&7>> &4ERROR #6"
error-button-not-pressed: "&b&lBot&d&lFilter&7>> &cВы не успели нажать на кнопку &7>> &4ERROR #7"
error-country-not-allowed: "&b&lBot&d&lFilter&7>> &cВаше соединение признано нелегитимным&7>> &4ERROR #4"
error-ping-is-too-big: "&b&lBot&d&lFilter&7>> &cУ вас слишком большой пинг. Возможно вы бот &7>> &4ERROR #8"
action-bar: "&cПинг: &f%ping% &8/ &cОнлайн на проверке: &f%online%"
#Включить ли постоянную защиту? 
#Если true, то будет включены проверки на прокси.
#И на GEO локации.
permanent-protection: false
#Время на сервере проверки.
#https://minecraft.gamepedia.com/File:Day_Night_Clock_24h.png
world-time: 18000
#Кикать ли ботов, если обнаружена атака.
#Если false, то боты могут зайти, а после успешной проверки их кикнет.
#Если true, то ботов будет кикать сразу, как только они попытаются зайти.
force-kick-bots-on-join-if-attack-detected: true
#Настройки проверки по пингу сервера.
server-ping-check:
  #Требовать ли от игроков пропинговать сервер, когда защита отключена?
  #если true то работает всегда
  on-normal-mode: false
  #Требовать ли от игроков пропинговать сервер, когда включена постоянная защита?
  on-permanent-protection: false
  #Требовать ли от игроков пропинговать сервер, когда обнаружена защита?
  on-bot-attack: true
  #Сколько секунд есть у игрока чтобы зайти на сервер после того как он пропинговал сервер
  time: 12
  kick-message: |-
    &cВы были кикнуты! Не используйте прямое подключение
    
    &bДля того чтобы зайти на сервер:
    
    &71) &rДобавте его в &lсписок серверов.
    
    &72) &rОбновите список серверов. 
    &oЧтобы обновить его нажмите кнопку &c&lОбновить &r&oили &c&lRefresh
    
    &73) &rПодождите &c1-3&r секунды и заходите!
    
#Кикать ли игроков ботов если пинг больше указаного значения?
#Работает только во время постоянной/автоматичекой защите. В обычном режиме не работает.
#-1 отключить
kick-if-ping-more-than: 220
#Как много игроков может проходить проверку за одну минуту
#Если данный порог превышен то включается лимит на прокси и на все страны кроме СНГ
#По логике, за минуту не должно заходить очень много игроков, которые не проходили проверку.
#Так что 20-30 достаточно. Если у вас ооочень большой онлайн то можно и 35-45 поставить.
#онлайна до 150 - 20
#онлайна от 150 до 250 - 30
#250-450 - 35-40
#выше 45
max-checks-per-1-min: 25
#Как долго будут действовать лимиты; В секундах.
protection-time: 70
#Показывать ли игроков/ботов в списке игроков при пинге сервера которые находятся на фильтре? 
show-filter-online: true
#Настройки проверки нажатии на кнопку.
button-check:
  #Включить ли проверку с помощью кнопки если не обноружена атака?
  #если true то работает всегда
  on-normal-mode: false
  #Включать ли проверку, если включена постоянная защита?
  on-permanent-protection: true
  #Включать ли проверку, если обнаружена бот атака?
  #Если значние выше false, а тут true и начнут бот атаку, то кнопка всёравно появится.
  on-bot-attack: true
#https://dev.maxmind.com/geoip/legacy/codes/iso3166/
#Страны которые могут входить на сервер пока включена автоматическая защита.
allowed-countries-auto: 
  - 'RU'
  - 'UA'
  - 'BY'
  - 'KZ'
  - 'EE'
  - 'GE'
  - 'MD'
#Дополнительные страны, которые могут входить, если включена постояная защита.
#В этот список также включаются страны из списка выше.
allowed-countries-permanent:
  - 'KG'
  - 'AZ'
mysql:
  enabled: false
  host: localhost
  port: "3306"
  username: root
  password: example
  database: botfilter
  #Для redis и прочих штук, которые позволяют использовать две и более бандж.
  #На прокси не работает.
  multibungee:
    enabled: false
    #Как часто синхронизировать аккаунты. В секундах
    #Слишком часто лучше не делать
    sync-time: 10
fake-online:
  enabled: false
  #ФЕЙК ОНЛАЙН ПОКАЗЫВАЕТСЯ ТОЛЬКО В QUERY И ПРИ ПИНГЕ СЕРВЕРА
  #НА ПЛАГИНЫ ОН НЕ ВЛИЯЕТ. ТОЛЬКО НА ТЕ ЧТО ИСПОЛЬЗУЮТ 'ProxyPingEvent'
  booster:
    #Эти заничения можно менять как угодно. Тоесть можно добавлять свои значения
    #Для буста онлайна. Т.е 0;150 , 70;200 и тд
    #от 0 до 30; Буст онлайна на 50%
    0;30: 1.5
    #от 31 до 60; Буст онлайна на 40%
    31;60: 1.4
    #от 61 до 100; Буст онлайна на 30%
    61;100: 1.3
    #любой другой онлайн, которого нет выше
    default: 1.25
proxy:
  #включить ли скачивание проксей.
  enabled: true
  #поддерживются списки, где на странице только прокси.
  #скачиваться будут только те прокси, страны которых включены в списки выше
  download-list:
  - https://lists.blocklist.de/lists/all.txt
  - http://www.ciarmy.com/list/ci-badguys.txt
  - http://danger.rulez.sk/projects/bruteforceblocker/blist.php
  - http://myip.ms/files/blacklist/csf/latest_blacklist.txt
  - http://tjfmc.de/DeathBot/SSlproxies.txt
  - http://tjfmc.de/DeathBot/Socks4.txt
  - http://tjfmc.de/DeathBot/Socks5.txt
  - http://151.80.108.152/proxy.txt
  blogspot-proxy:
  #- url;regex   - default regex: href=\'(.*?)\'
  - http://socksproxylist24.blogspot.com/
  - http://www.vipsocks24.net/
  - http://www.socks24.org/
  - http://www.live-socks.net/
  - http://www.proxyserverlist24.top/
  - http://www.sslproxies24.top/
  - http://proxy-daily.com/;href=\"(.*?)\"
config-version: 5