msg-check: "&b&lBot&d&lFilter&7>> &fОжидайте завершения проверки..."
msg-check-2: "&b&lBot&d&lFilter&7>> &fНажимите на кнопку с &aЗЕЛЁНОЙ&f шерстью."
msg-check-sus: "&b&lBot&d&lFilter&7>> &aПроверка пройдена"
error-many-checks: "&b&lBot&d&lFilter&7>> &cОчень много проверок с одного IP адресса. Попробуйте зайти через 10 минут&7>> &4ERROR #0" 
error-not-a-player: "&b&lBot&d&lFilter&7>> &cСкорее всего вы не игрок &a(Если вы используете читы, выключите их) &7>> &4ERROR #1"
error-wrong-button: "&b&lBot&d&lFilter&7>> &cВы нажали на неверную кнопку&7>> &4ERROR #5"
error-proxy-detected: "&b&lBot&d&lFilter&7>> &cВаше соединение признано нелегитимным&7>> &4ERROR #2"
error-many-pos-packets: "&b&lBot&d&lFilter&7>> &cВы посылаете очень много пакетов&7>> &4ERROR #3"
error-cannot-use-button : "&b&lBot&d&lFilter&7>> &cНеправильная позиция&7>> &4ERROR #6"
error-country-not-allowed: "&b&lBot&d&lFilter&7>> &cВаше соединение признано нелегитимным&7>> &4ERROR #4"
#Включить ли постоянную защиту? 
#Если true, то будет включены проверки на прокси.
#И на GEO локации.
permanent-protection: false
#Кикать ли ботов, если обнаружена атака.
#Если false, то боты могут зайти, а после успешной проверки их кикнет.
#Если true, то ботов будет кикать сразу, как только они попытаются зайти.
force-kick-bots-on-join-if-attack-detected: true
#Как много игроков может проходить проверку за одну минуту
#Если данный порог превышен то включается лимит на прокси и на все страны кроме СНГ
#По логике, за минуту не должно заходить очень много игроков, которые не проходили проверку.
#Так что 20-30 достаточно. Если у вас ооочень большой онлайн то можно и 35-45 поставить.
#онлайна до 150 - 20
#онлайна от 150 до 250 - 30
#250-450 - 35-40
#выше 45
max-checks-per-1-min: 25
#Как долго будут действовать лимиты; В секундах.
protection-time: 70
#Настройки проверки нажатии на кнопку.
button-check:
  #Включить ли проверку с помощью кнопки если не обноружена атака?
  on-normal-mode: false
  #Включать ли проверку, если включена постоянная защита?
  on-permanent-protection: true
  #Включать ли проверку, если обнаружена бот атака?
  #Если значние выше false, а тут true и начнут бот атаку, то кнопка всёравно появится.
  on-bot-attack: true
#https://dev.maxmind.com/geoip/legacy/codes/iso3166/
#Страны которые могут входить на сервер пока включена автоматическая защита.
allowed-countries-auto: 
  - 'RU'
  - 'UA'
  - 'BY'
  - 'KZ'
  - 'EE'
  - 'GE'
  - 'MD'
#Дополнительные страны, которые могут входить, если включена постояная защита.
#В этот список также включаются страны из списка выше.
allowed-countries-permanent:
  - 'KG'
  - 'AZ'
mysql:
  enabled: false
  host: localhost
  port: "3306"
  username: root
  password: example
  database: botfilter
fake-online:
  enabled: false
  #ФЕЙК ОНЛАЙН ПОКАЗЫВАЕТСЯ ТОЛЬКО В QUERY И ПРИ ПИНГЕ СЕРВЕРА
  #НА ПЛАГИНЫ ОН НЕ ВЛИЯЕТ. ТОЛЬКО НА ТЕ ЧТО ИСПОЛЬЗУЮТ 'ProxyPingEvent'
  booster:
    #Эти заничения можно менять как угодно. Тоесть можно добавлять свои значения
    #Для буста онлайна. Т.е 0;150 , 70;200 и тд
    #от 0 до 30; Буст онлайна на 50%
    0;30: 1.5
    #от 31 до 60; Буст онлайна на 40%
    31;60: 1.4
    #от 61 до 100; Буст онлайна на 30%
    61;100: 1.3
    #любой другой онлайн, которого нет выше
    default: 1.25
config-version: 2